### ISSUE TITLE
数字签名正常但是证书已吊销

### ISSUE THREAD

**Issue by Cross2pro** [JemmyLoveJenny/HookSigntool#11]
![QQ截图20230807102034](https://github.com/Jemmy1228/HookSigntool/assets/30151531/a4213d74-f739-43d4-85b5-0d8bea40a6a6)
![QQ截图20230807102044](https://github.com/Jemmy1228/HookSigntool/assets/30151531/c9486dc0-6010-4921-9021-dd531e2450ab)
你好，请问数字签名正常但是加载驱动显示已吊销该怎么解决

**Comment by D3it7i** [comment]
这是由于微软的KB5028166补丁导致，貌似修改/或者删除了某些签名判断机制。

**Comment by ghost** [comment]
Win11和新版Win10都这样，先试试删掉KB5028166补丁，不然一切方法都无效。

确认删了之后，卸载驱动重试。
如果仍然不行的话，只有三个方案：
方案0.每次开机按F8，禁用强制签名。麻烦。
方案1.换个证书，可能需要多试几次，大部分证书都被微软拉黑了。而且治标不治本，微软可能在半年后把剩下的证书继续拉黑。（如果你有自己买的2015年7月29日之前颁发的代码签名证书无视）

方案2.降级系统到LTSB2016，或者降级到LTSC2019也可以。100%解决。如果使用LTSC2019，必须使用原版未集成补丁系统，离线断网安装，安装完成后除了移除Flash的补丁外(这个补丁如果装的话，也必须离线安装。不必须装，自愿)不能再打任何补丁，必须在第一次联网前使用Windows Update Blocker彻底禁用系统更新，然后再用Dism++ --- 系统优化---安全相关设置，关闭Windows Defender，再联网。联网后不要再开启Windows更新和Defender。可以登录微软账号，不受影响。2016不用特殊操作，直接用，只要导入了时间戳证书就行。
