### ISSUE TITLE
关于添加自定义时间戳

### ISSUE THREAD

**Issue by Jotalz** [JemmyLoveJenny/HookSigntool#14]
大佬能不能讲解一下具体替换哪些，我使用winhex打开亚洲诚信搜索http相关字符串很多，包含sha256的有2-3个，没有找到包含sha1的，我是需要把它们都替换为CustomTimestampMarker-SHA256吗？

**Comment by PIKACHUIM** [comment]
需要修改DLL Hook源码，参考：
https://code.99pika.com/index.php/archives/277/#VS%E7%BC%96%E8%AF%91HookSigntool

**Comment by Jotalz** [comment]
> 需要修改DLL Hook源码，参考： https://code.99pika.com/index.php/archives/277/#VS%E7%BC%96%E8%AF%91HookSigntool

多谢大佬！
