### ISSUE TITLE
SHA2 时间戳摘要算法问题

### ISSUE THREAD

**Issue by hauntek** [JemmyLoveJenny/HookSigntool#4]
![image](https://user-images.githubusercontent.com/17927997/118866664-cde8c280-b914-11eb-8329-c9b2be577f8d.png)

SHA256 时间戳签名 摘要算法不是sha256, 还是sha1算法的

http://tsa.pki.jemmylovejenny.tk/SHA256/2011-04-01T00:00:00

**Comment by hauntek** [comment]
主数字证书是 sha256算法，副署时间戳证书算法是sha1

**Comment by Jemmy1228** [comment]
这个算法和你选用的签名协议有关，Authenticode和RFC3161
网址中的SHA256的意思是说，时间戳证书链使用SHA256签名的，并不代表签名算法
你截图里的签名是用Authenticode协议签上的，只能用SHA1摘要
如果想要用SHA256，那就只能用RFC3161协议（/t改成/tr）

```
signtool timestamp /t "http://tsa.pki.jemmylovejenny.tk/SHA1/2011-04-01T00:00:00" test.exe
signtool timestamp /tp 1 /tr "http://tsa.pki.jemmylovejenny.tk/SHA256/2011-04-01T00:00:00" test.exe
```

**Comment by hauntek** [comment]
```
signtool sign /f pfx.pfx /p pass /ac MSCV-VeriSign.cer /tr http://tsa.pki.jemmylovejenny.tk/SHA1/2011-08-08T00:00:00 /fd sha1 /v sys.sys
signtool sign /f pfx.pfx /p pass /ac MSCV-VeriSign.cer /tr http://tsa.pki.jemmylovejenny.tk/SHA256/2011-08-08T00:00:00 /as /fd sha256 /v sys.sys
```

这是我签名的命令，我是用/tr 的，时间戳还是SHA1摘要

**Comment by hauntek** [comment]
![image](https://user-images.githubusercontent.com/17927997/118916298-42e1e980-b961-11eb-88d1-bac4293d34f5.png)
![image](https://user-images.githubusercontent.com/17927997/118916320-4aa18e00-b961-11eb-98a4-f2a8dbbd738e.png)

**Comment by hauntek** [comment]
我用的是双签名.

第一个签名，sha1摘要算法，主数字证书摘要算法，时间戳副署摘要算法 均为sha1，正常
第二个签名，sha256摘要算法，主数字证书摘要算法sha256，时间戳副署摘要算法为sha1，不一致

签名采用/tr http://tsa.pki.jemmylovejenny.tk/SHA256/2011-04-01T00:00:00

**Comment by Jemmy1228** [comment]
加上`/td sha256`，`/fd`是指定签名算法的，`/td`指定时间戳算法

**Comment by hauntek** [comment]
![image](https://user-images.githubusercontent.com/17927997/118971703-53668400-b9a2-11eb-8146-d0ec879e6c7f.png)

加上`/td sha256`，确实就是sha256了，帮了大忙了，谢谢，这个时间戳服务很好用，自定义时间功能很棒！
