### ISSUE TITLE
时间戳服务器

### ISSUE THREAD

**Issue by Jhinxs** [JemmyLoveJenny/HookSigntool#5]
帅哥 时间戳服务器访问不了 是我的网络问题吗

**Comment by Jemmy1228** [comment]
中国移动或者一些小运营商可能屏蔽了那个域名

**Comment by Jhinxs** [comment]
我i挂了代理可以用了 但是我在win10 21h1的系统上用你的伪造的时间戳服务器那一套操作 签名是正常的，但是我把文件拷贝到20h1的win10虚拟机上，就不行了，显示吊销或者是什么签署副本更改啥的

**Comment by Jemmy1228** [comment]
那是因为虚拟机不信任我的根证书

访问 https://github.com/JemmyLoveJenny/HookSigntool/releases/latest 下载最新的发布
压缩包内有一个EVRootCA.reg，双击导入即可

**Comment by Jhinxs** [comment]
请问有没有通用一点的呢方法呢 就是说我自己修改了之后，倒别的机器上就直接能用的，能经过验证的那种，感谢

Jemmy Wang ***@***.***> 于2021年8月9日周一 下午9:43写道：

**Comment by ttimasdf** [comment]
做黑产还想白嫖？呵呵，想得真美
